### PR TITLE
Develop ml strategy

### PR DESCRIPTION
**Pull request by lipebento1**
Pytests for all strategies. Had to change a lot of things. Take a look pls!

### CODE REVIEW

**Review by judymao — DISMISSED** [review]
Local files are being referenced. Make sure to reference the files in the data folder that anyone can access!

**Review by judymao — CHANGES_REQUESTED** [review]
Can we rename MLStrt as MLStrat?

**Review by dzhang98 — DISMISSED** [review]
I fixed the typo for MLStrat. However, could you please change some of your ValueErrors to TypeErrors? TypeError is when it the incorrect type is passed in (e.g. function expects an integer but receives a string), while ValueError is when the incorrect value is passed in (e.g. function expects a positive number but receives a negative number).

**Review by judymao — DISMISSED** [review]
I think you removed a lot of value and type checks from the predict_returns function. Could you put them back in strategies.py (lines 557-573 were removed). The test_ML_predict_returns test was also removed, could you add that back in as well (in test_strategies.py, originally lines 52-69)? This was done to test the predict_returns function in particular, which is a special case separate from all the other strategy classes, so it should have its own test I think. Thanks!

**Review by dzhang98 — DISMISSED** [review]
Could you describe what risk_free is in the docstring for the TrendFollowing class __init__ function?

**Review by judymao — COMMENTED** [review]
I've changed some variable names, adjusted some data cleaning so it no longer has to be done every time, and removed some unnecessary variables / imports / comments.

**Review by judymao — APPROVED** [review]
Looks good to me

**Review by dzhang98 — APPROVED** [review]
Looks good.

**Pull request merged**
