### PR TITLE
Strategy development

### PR DESCRIPTION
**Pull request by lipebento1**
Hi team. I added a couple of things, including a couple of strategies and I made some changes to make the strategy/backtest integration more smooth.

Please take a look before we merge into main! 

Thanks

### CODE REVIEW

**Comment by dzhang98** [comment]
Looks good to me!

**Comment by judymao** [comment]
For the unit tests, is a loop the most efficient way of computing that check?

**Comment by lipebento1** [comment]
Good point @judymao. The issue I faced was that pytest.approx only works for comparing floats and since we need to do a test for everyday in the dataframe I compared everyday ( which is a float) in a loop. We are running a bit out of time so I didn't look too much into it, but if you find a more efficient way please let me know!

**Comment by judymao** [comment]
I think you can compare using .values so that you don't need the loop anymore! I've made the change :)

**Comment by dzhang98** [comment]
Great, I'll close it now!

**Comment by judymao** [comment]
Reviewed above!

**Review by judymao — COMMENTED** [review]
Thanks for adding new strategy classes and for updating the docstrings! After the changes made in the discussion (ie improving efficiency through removing some for loops), I think everything looks good. 

One thing to try in future is to compute returns internally using price data rather than passing them as a separate dataset.

**Review by dzhang98 — COMMENTED** [review]
Looks good!

**Pull request merged**
