### PR TITLE
Develop ML strategy

### PR DESCRIPTION
**Pull request by dzhang98**
I've developed the machine learning strategy so that it returns a time series of weights for each stock, similar to what the other strategies have done. Please let me know if it looks good!

### CODE REVIEW

**Comment by judymao** [comment]
Looking good! I noticed that the pytests for the ML class are missing. I can add tests for the function I wrote!

**Comment by dzhang98** [comment]
> Looking good! I noticed that the pytests for the ML class are missing. I can add tests for the function I wrote!

Thanks for catching that! I'll work on some on my end as well for the get_weights() function.

**Comment by judymao** [comment]
> > Looking good! I noticed that the pytests for the ML class are missing. I can add tests for the function I wrote!
> 
> Thanks for catching that! I'll work on some on my end as well for the get_weights() function.

I think you were missing some commits from the main branch (I just added them). We can work in the test_strategies file

**Comment by judymao** [comment]
I added my test! I also noticed that get_weights requires at least 5 stocks to work, you should probably add a test for that. I accounted for it in the get_weights function already.

**Comment by dzhang98** [comment]
Updated some of my tests too!

**Review by judymao — CHANGES_REQUESTED** [review]
The changes thus far seem good (refer to previous comments), however I noticed some tests are commented out. Is it because the architecture to pass them isn't set up yet in the new strategy class? Let's fix thee tests before merging into main.

**Comment by lipebento1** [comment]
I think that the final weights of your strategy's output are not summing up to 1. I will see if I can do anything about it.

**Review by lipebento1 — APPROVED** [review]
Seems great now!

**Review by judymao — APPROVED** [review]
Thanks for making the changes!

**Pull request merged**
