### PR TITLE
Build ML Model

### PR DESCRIPTION
**Pull request by judymao**
Added a machine learning model-based Strategy class (MachineLearningMethod) that uses two methods: linear regression and random forest regression to predict future stock returns. Other minor changes include removing some unused packages. To do still: developing a method to get weights utilizing the output from the MachineLearningMethod.predict_returns() function.

### CODE REVIEW

**Comment by dzhang98** [comment]
Looks good! I will build on this model to generate weights for the portfolio. I will also add Pytests.

**Comment by lipebento1** [comment]
Good code. Just one thing, in the docstring you missed a description for the parameter "model".

**Comment by judymao** [comment]
Thanks for noticing! Added, please close this request if all else looks good!

**Review by lipebento1 — COMMENTED** [review]
Everything looks great!

**Review by dzhang98 — COMMENTED** [review]
Looks good to me!

**Pull request merged**
